/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LeapplayJsClient) {
      root.LeapplayJsClient = {};
    }
    root.LeapplayJsClient.RequestTokenRefresh = factory(root.LeapplayJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RequestTokenRefresh model module.
   * @module model/RequestTokenRefresh
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestTokenRefresh</code>.
   * @alias module:model/RequestTokenRefresh
   * @class
   * @param refreshToken {String} 
   */
  var exports = function(refreshToken) {
    var _this = this;

    _this['refreshToken'] = refreshToken;
  };

  /**
   * Constructs a <code>RequestTokenRefresh</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestTokenRefresh} obj Optional instance to populate.
   * @return {module:model/RequestTokenRefresh} The populated <code>RequestTokenRefresh</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('refreshToken')) {
        obj['refreshToken'] = ApiClient.convertToType(data['refreshToken'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} refreshToken
   */
  exports.prototype['refreshToken'] = undefined;



  return exports;
}));


