/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LeapplayJsClient) {
      root.LeapplayJsClient = {};
    }
    root.LeapplayJsClient.RequestRegisterUser = factory(root.LeapplayJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RequestRegisterUser model module.
   * @module model/RequestRegisterUser
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestRegisterUser</code>.
   * @alias module:model/RequestRegisterUser
   * @class
   * @param username {String} 
   * @param eMailAddress {String} 
   * @param password {String} 
   */
  var exports = function(username, eMailAddress, password) {
    var _this = this;

    _this['username'] = username;
    _this['eMailAddress'] = eMailAddress;
    _this['password'] = password;
  };

  /**
   * Constructs a <code>RequestRegisterUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestRegisterUser} obj Optional instance to populate.
   * @return {module:model/RequestRegisterUser} The populated <code>RequestRegisterUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('eMailAddress')) {
        obj['eMailAddress'] = ApiClient.convertToType(data['eMailAddress'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {String} eMailAddress
   */
  exports.prototype['eMailAddress'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;



  return exports;
}));


