/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LeapplayJsClient) {
      root.LeapplayJsClient = {};
    }
    root.LeapplayJsClient.RequestEmailConfirmation = factory(root.LeapplayJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RequestEmailConfirmation model module.
   * @module model/RequestEmailConfirmation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestEmailConfirmation</code>.
   * @alias module:model/RequestEmailConfirmation
   * @class
   * @param username {String} 
   * @param emailConfirmationToken {String} 
   */
  var exports = function(username, emailConfirmationToken) {
    var _this = this;

    _this['username'] = username;
    _this['emailConfirmationToken'] = emailConfirmationToken;
  };

  /**
   * Constructs a <code>RequestEmailConfirmation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestEmailConfirmation} obj Optional instance to populate.
   * @return {module:model/RequestEmailConfirmation} The populated <code>RequestEmailConfirmation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('emailConfirmationToken')) {
        obj['emailConfirmationToken'] = ApiClient.convertToType(data['emailConfirmationToken'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {String} emailConfirmationToken
   */
  exports.prototype['emailConfirmationToken'] = undefined;



  return exports;
}));


