/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LeapplayJsClient) {
      root.LeapplayJsClient = {};
    }
    root.LeapplayJsClient.RequestChangePassword = factory(root.LeapplayJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RequestChangePassword model module.
   * @module model/RequestChangePassword
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestChangePassword</code>.
   * @alias module:model/RequestChangePassword
   * @class
   * @param currentPassword {String} 
   * @param newPassword {String} 
   */
  var exports = function(currentPassword, newPassword) {
    var _this = this;

    _this['currentPassword'] = currentPassword;
    _this['newPassword'] = newPassword;
  };

  /**
   * Constructs a <code>RequestChangePassword</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestChangePassword} obj Optional instance to populate.
   * @return {module:model/RequestChangePassword} The populated <code>RequestChangePassword</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('currentPassword')) {
        obj['currentPassword'] = ApiClient.convertToType(data['currentPassword'], 'String');
      }
      if (data.hasOwnProperty('newPassword')) {
        obj['newPassword'] = ApiClient.convertToType(data['newPassword'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} currentPassword
   */
  exports.prototype['currentPassword'] = undefined;
  /**
   * @member {String} newPassword
   */
  exports.prototype['newPassword'] = undefined;



  return exports;
}));


