/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LeapplayJsClient) {
      root.LeapplayJsClient = {};
    }
    root.LeapplayJsClient.Session = factory(root.LeapplayJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Session model module.
   * @module model/Session
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Session</code>.
   * @alias module:model/Session
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Session</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Session} obj Optional instance to populate.
   * @return {module:model/Session} The populated <code>Session</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('sessionId')) {
        obj['sessionId'] = ApiClient.convertToType(data['sessionId'], 'String');
      }
      if (data.hasOwnProperty('reference')) {
        obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('startedOnUtc')) {
        obj['startedOnUtc'] = ApiClient.convertToType(data['startedOnUtc'], 'Date');
      }
      if (data.hasOwnProperty('startDuration')) {
        obj['startDuration'] = ApiClient.convertToType(data['startDuration'], 'String');
      }
      if (data.hasOwnProperty('maxDurationLimit')) {
        obj['maxDurationLimit'] = ApiClient.convertToType(data['maxDurationLimit'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} sessionId
   */
  exports.prototype['sessionId'] = undefined;
  /**
   * @member {String} reference
   */
  exports.prototype['reference'] = undefined;
  /**
   * @member {module:model/Session.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {Date} startedOnUtc
   */
  exports.prototype['startedOnUtc'] = undefined;
  /**
   * @member {String} startDuration
   */
  exports.prototype['startDuration'] = undefined;
  /**
   * @member {String} maxDurationLimit
   */
  exports.prototype['maxDurationLimit'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "Requested"
     * @const
     */
    "Requested": "Requested",
    /**
     * value: "Delivered"
     * @const
     */
    "Delivered": "Delivered",
    /**
     * value: "Started"
     * @const
     */
    "Started": "Started",
    /**
     * value: "Ended"
     * @const
     */
    "Ended": "Ended",
    /**
     * value: "Canceled"
     * @const
     */
    "Canceled": "Canceled",
    /**
     * value: "DeliveryTimeout"
     * @const
     */
    "DeliveryTimeout": "DeliveryTimeout",
    /**
     * value: "ResponseTimeout"
     * @const
     */
    "ResponseTimeout": "ResponseTimeout"  };


  return exports;
}));


