/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangeRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChangeRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.LeapplayJsClient) {
      root.LeapplayJsClient = {};
    }
    root.LeapplayJsClient.SessionLog = factory(root.LeapplayJsClient.ApiClient, root.LeapplayJsClient.ChangeRequest);
  }
}(this, function(ApiClient, ChangeRequest) {
  'use strict';




  /**
   * The SessionLog model module.
   * @module model/SessionLog
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SessionLog</code>.
   * @alias module:model/SessionLog
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>SessionLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SessionLog} obj Optional instance to populate.
   * @return {module:model/SessionLog} The populated <code>SessionLog</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('stationId')) {
        obj['stationId'] = ApiClient.convertToType(data['stationId'], 'String');
      }
      if (data.hasOwnProperty('sessionId')) {
        obj['sessionId'] = ApiClient.convertToType(data['sessionId'], 'String');
      }
      if (data.hasOwnProperty('requestedBy')) {
        obj['requestedBy'] = ApiClient.convertToType(data['requestedBy'], 'String');
      }
      if (data.hasOwnProperty('latestState')) {
        obj['latestState'] = ApiClient.convertToType(data['latestState'], 'String');
      }
      if (data.hasOwnProperty('startedUtc')) {
        obj['startedUtc'] = ApiClient.convertToType(data['startedUtc'], 'Date');
      }
      if (data.hasOwnProperty('reference')) {
        obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
      }
      if (data.hasOwnProperty('maxDurationLimit')) {
        obj['maxDurationLimit'] = ApiClient.convertToType(data['maxDurationLimit'], 'String');
      }
      if (data.hasOwnProperty('endedUtc')) {
        obj['endedUtc'] = ApiClient.convertToType(data['endedUtc'], 'Date');
      }
      if (data.hasOwnProperty('stoppedBy')) {
        obj['stoppedBy'] = ApiClient.convertToType(data['stoppedBy'], 'String');
      }
      if (data.hasOwnProperty('changeRequests')) {
        obj['changeRequests'] = ApiClient.convertToType(data['changeRequests'], [ChangeRequest]);
      }
    }
    return obj;
  }

  /**
   * @member {String} stationId
   */
  exports.prototype['stationId'] = undefined;
  /**
   * @member {String} sessionId
   */
  exports.prototype['sessionId'] = undefined;
  /**
   * @member {module:model/SessionLog.RequestedByEnum} requestedBy
   */
  exports.prototype['requestedBy'] = undefined;
  /**
   * @member {module:model/SessionLog.LatestStateEnum} latestState
   */
  exports.prototype['latestState'] = undefined;
  /**
   * @member {Date} startedUtc
   */
  exports.prototype['startedUtc'] = undefined;
  /**
   * @member {String} reference
   */
  exports.prototype['reference'] = undefined;
  /**
   * @member {String} maxDurationLimit
   */
  exports.prototype['maxDurationLimit'] = undefined;
  /**
   * @member {Date} endedUtc
   */
  exports.prototype['endedUtc'] = undefined;
  /**
   * @member {module:model/SessionLog.StoppedByEnum} stoppedBy
   */
  exports.prototype['stoppedBy'] = undefined;
  /**
   * @member {Array.<module:model/ChangeRequest>} changeRequests
   */
  exports.prototype['changeRequests'] = undefined;


  /**
   * Allowed values for the <code>requestedBy</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RequestedByEnum = {
    /**
     * value: "Undefined"
     * @const
     */
    "Undefined": "Undefined",
    /**
     * value: "ShellClient"
     * @const
     */
    "ShellClient": "ShellClient",
    /**
     * value: "WebApi"
     * @const
     */
    "WebApi": "WebApi"  };

  /**
   * Allowed values for the <code>latestState</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LatestStateEnum = {
    /**
     * value: "Requested"
     * @const
     */
    "Requested": "Requested",
    /**
     * value: "Delivered"
     * @const
     */
    "Delivered": "Delivered",
    /**
     * value: "Started"
     * @const
     */
    "Started": "Started",
    /**
     * value: "Ended"
     * @const
     */
    "Ended": "Ended",
    /**
     * value: "Canceled"
     * @const
     */
    "Canceled": "Canceled",
    /**
     * value: "DeliveryTimeout"
     * @const
     */
    "DeliveryTimeout": "DeliveryTimeout",
    /**
     * value: "ResponseTimeout"
     * @const
     */
    "ResponseTimeout": "ResponseTimeout"  };

  /**
   * Allowed values for the <code>stoppedBy</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StoppedByEnum = {
    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown",
    /**
     * value: "UserLogout"
     * @const
     */
    "UserLogout": "UserLogout",
    /**
     * value: "RemoteLogout"
     * @const
     */
    "RemoteLogout": "RemoteLogout",
    /**
     * value: "Inactivity"
     * @const
     */
    "Inactivity": "Inactivity",
    /**
     * value: "StationShutdown"
     * @const
     */
    "StationShutdown": "StationShutdown",
    /**
     * value: "LimitReached"
     * @const
     */
    "LimitReached": "LimitReached",
    /**
     * value: "ConnectionLoss"
     * @const
     */
    "ConnectionLoss": "ConnectionLoss",
    /**
     * value: "SubscriptionEnded"
     * @const
     */
    "SubscriptionEnded": "SubscriptionEnded"  };


  return exports;
}));


