/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LeapplayJsClient) {
      root.LeapplayJsClient = {};
    }
    root.LeapplayJsClient.StationSettings = factory(root.LeapplayJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StationSettings model module.
   * @module model/StationSettings
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>StationSettings</code>.
   * @alias module:model/StationSettings
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>StationSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StationSettings} obj Optional instance to populate.
   * @return {module:model/StationSettings} The populated <code>StationSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('stationId')) {
        obj['stationId'] = ApiClient.convertToType(data['stationId'], 'String');
      }
      if (data.hasOwnProperty('displayName')) {
        obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
      }
      if (data.hasOwnProperty('qrCode')) {
        obj['qrCode'] = ApiClient.convertToType(data['qrCode'], 'String');
      }
      if (data.hasOwnProperty('controlMode')) {
        obj['controlMode'] = ApiClient.convertToType(data['controlMode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} stationId
   */
  exports.prototype['stationId'] = undefined;
  /**
   * @member {String} displayName
   */
  exports.prototype['displayName'] = undefined;
  /**
   * @member {String} qrCode
   */
  exports.prototype['qrCode'] = undefined;
  /**
   * @member {module:model/StationSettings.ControlModeEnum} controlMode
   */
  exports.prototype['controlMode'] = undefined;


  /**
   * Allowed values for the <code>controlMode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ControlModeEnum = {
    /**
     * value: "Undefined"
     * @const
     */
    "Undefined": "Undefined",
    /**
     * value: "Local"
     * @const
     */
    "Local": "Local",
    /**
     * value: "Remote"
     * @const
     */
    "Remote": "Remote",
    /**
     * value: "RemoteWithQrCode"
     * @const
     */
    "RemoteWithQrCode": "RemoteWithQrCode"  };


  return exports;
}));


