/**
 * Leap Play
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LeapplayJsClient);
  }
}(this, function(expect, LeapplayJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LeapplayJsClient.SessionLog();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SessionLog', function() {
    it('should create an instance of SessionLog', function() {
      // uncomment below and update the code to test SessionLog
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be.a(LeapplayJsClient.SessionLog);
    });

    it('should have the property stationId (base name: "stationId")', function() {
      // uncomment below and update the code to test the property stationId
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property sessionId (base name: "sessionId")', function() {
      // uncomment below and update the code to test the property sessionId
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property requestedBy (base name: "requestedBy")', function() {
      // uncomment below and update the code to test the property requestedBy
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property latestState (base name: "latestState")', function() {
      // uncomment below and update the code to test the property latestState
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property startedUtc (base name: "startedUtc")', function() {
      // uncomment below and update the code to test the property startedUtc
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property maxDurationLimit (base name: "maxDurationLimit")', function() {
      // uncomment below and update the code to test the property maxDurationLimit
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property endedUtc (base name: "endedUtc")', function() {
      // uncomment below and update the code to test the property endedUtc
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property stoppedBy (base name: "stoppedBy")', function() {
      // uncomment below and update the code to test the property stoppedBy
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

    it('should have the property changeRequests (base name: "changeRequests")', function() {
      // uncomment below and update the code to test the property changeRequests
      //var instance = new LeapplayJsClient.SessionLog();
      //expect(instance).to.be();
    });

  });

}));
